#plot3
library(devtools)
library(dplyr)
library(data.table)
library(lubridate)
electricity<-fread("household_power_consumption.txt")
elec<-subset(electricity,Date=="1/2/2007" | Date=="2/2/2007")
elec$Date<-as.Date(elec$Date,format="%d/%m/%Y")
elec$datetime=paste(elec$Date,elec$Time,sep = " ")
elec$datetime=ymd_hms(elec$datetime,tz=Sys.timezone())
elec$Sub_metering_1<-as.numeric(as.character(elec$Sub_metering_1))
elec$Sub_metering_2<-as.numeric(as.character(elec$Sub_metering_2))
elec$Sub_metering_3<-as.numeric(as.character(elec$Sub_metering_3))
with(elec,plot(datetime,Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")) 
with(elec,lines(datetime,Sub_metering_2,col="red")) 
with(elec,lines(datetime,Sub_metering_3,col="blue")) 
legend("topright",col=c("black","red","blue"),lty = 1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.6)
dev.copy(png,'plot3.png')
dev.off()