#plot2
library(devtools)
library(dplyr)
library(data.table)
library(lubridate)
electricity<-fread("household_power_consumption.txt")
elec<-subset(electricity,Date=="1/2/2007" | Date=="2/2/2007")
elec$Date<-as.Date(elec$Date,format="%d/%m/%Y")
elec$datetime=paste(elec$Date,elec$Time,sep = " ")
elec$datetime=ymd_hms(elec$datetime,tz=Sys.timezone())
elec$Global_active_power<-as.numeric(as.character(elec$Global_active_power))
with(elec,plot(datetime,Global_active_power,type="l",ylab="Global Active Power(kilowatts)")) 
dev.copy(png,'plot2.png')
dev.off()